before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FzwZ1TDRNknkTWguGLJQOi1cg/AS5OFmEl+vWEtLMyxTVeKcLZQ3x1QM6l2Vo6pAPy1U8IalaGcH/c7g1BraSC/M+LWVWdk/qANfaJyOU80YvLUQPPewT0WFFtQoZ6nK+ZcdT+tO15qfzxtKoVKr2DtROJKYS90iKpOi8wpfSpH0YpeQXjpB6CHy5vkGjlWBBrBSk1geThSakP6erSlgdKhZp6NR3ty+Wvw+6Vw3NnWpXYPs1NkWhIgvLib0/zFucdQtXTuiGIvY95rGQrDJDPn/WBNx9wMGYsyuE2UoECHie6jkRnuXfnHwnvv+4KzA7rEMYFy7CH5hk/68CTAJqFBMfEQZ7/ZGpBFjobug7aEga9bYeqfpgsIgvG21mSqfOwWRrS/Sa+E9EJh9vdnEkZHbZCpgQRpFVxPFcxblrqo0pC72TVcyao/GrpaSvXHRLZhicIVfYuDyRHHzKD/tlYG364+bxLvvkECKWU5XQBNRZmdfxaM8I209MyafxfWtbC4XuLym13moFu00QDN5MZENYjl9g61vBWfy59IuG92PWC3cABJskip+/Lok1cpx9C8hrafv6Hvuf9L1WMbDGJmfeFUhF9sudjCECJ275RPmueZhOGarpflJPdFK3eTxvFMy/y2sodKcHPyn+aYPsZPRgQl7/E8Ywoa/Z3m9hX4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
